# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2d86b954-636f-4448-8fbf-86180389b796";
      fsType = "ext4";
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/3AA8-4B73";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/btrfs" =
    { device = "/dev/disk/by-uuid/387a26e9-e48e-4acc-953e-faf9ff2d38f7";
      fsType = "btrfs";
    };

  fileSystems."/mnt/data" =
   { device = "/dev/disk/by-uuid/4E8BF8824E68DB3B";
     fsType = "ntfs-3g";
     options = [ "rw" ];
   };

  fileSystems."/mnt/win" =
   { device = "/dev/disk/by-uuid/DC2EA9F32EA9C73C";
     fsType = "ntfs-3g";
     options = [ "rw" ];
   };

  fileSystems."/mnt/ssd1" =
   { device = "/dev/disk/by-uuid/825AAA2A5AAA1AC5";
     fsType = "ntfs-3g";
     options = [ "rw" ];
   };

#fileSystems."/mnt/kodi" = 
# { device = "//192.168.0.102/kodi";
#    fsType = "cifs";
#    options = [
#      "credentials=/root/.smbcredentials"
#      "vers=3.0"
#      "_netdev"
#      "nofail"
#      "x-systemd.automount"
#      "x-systemd.idle-timeout=30"
#    ];
# };

  boot.initrd.systemd.enable = true;
  swapDevices =
    [ { device = "/var/lib/swapfile";
        size = 12*1024;
    }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
